### ISSUE TITLE
 apache-2  not in activemode

### ISSUE THREAD

**Issue by chinnadas** [asquarezone/AnsibleZone#1]
ansible@ip-172-31-22-72:~/playbooks$ sudo vi apache.yml
ansible@ip-172-31-22-72:~/playbooks$ ansible-playbook apache.yml

PLAY [all] ***************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************
ok: [ip-172-31-38-231.us-west-2.compute.internal]
ok: [ip-172-31-37-173.us-west-2.compute.internal]
ok: [localhost]

TASK [installing apache] *************************************************************************************************************
ok: [ip-172-31-37-173.us-west-2.compute.internal]
ok: [localhost]
ok: [ip-172-31-38-231.us-west-2.compute.internal]

TASK [restart apache] ****************************************************************************************************************
fatal: [ip-172-31-37-173.us-west-2.compute.internal]: FAILED! => {"changed": false, "msg": "value of state must be one of: reloaded, restarted, started, stopped, got: restart"}
fatal: [ip-172-31-38-231.us-west-2.compute.internal]: FAILED! => {"changed": false, "msg": "value of state must be one of: reloaded, restarted, started, stopped, got: restart"}
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: reloaded, restarted, started, stopped, got: restart"}
        to retry, use: --limit @/home/ansible/playbooks/apache.retry

PLAY RECAP ***************************************************************************************************************************
ip-172-31-37-173.us-west-2.compute.internal : ok=2    changed=0    unreachable=0    failed=1
ip-172-31-38-231.us-west-2.compute.internal : ok=2    changed=0    unreachable=0    failed=1
localhost                  : ok=2    changed=0    unreachable=0    failed=1

ansible@ip-172-31-22-72:~/playbooks$ sudo service apache2 status
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: inactive (dead) since Tue 2018-11-20 17:00:32 UTC; 27min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 8642 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 8625 ExecStart=/etc/init.d/apache2 start (code=exited, status=0/SUCCESS)

Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: no listening sockets available, shutting down
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: AH00015: Unable to open logs
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: Action 'start' failed.
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: The Apache error log may have more information.
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]:  *
Nov 20 17:00:32 ip-172-31-22-72 apache2[8642]:  * Stopping Apache httpd web server apache2
Nov 20 17:00:32 ip-172-31-22-72 apache2[8642]:  *
Nov 20 17:00:32 ip-172-31-22-72 systemd[1]: Started LSB: Apache2 web server.

**Comment by BRAHMAREDDYV** [comment]
Not the issues are posted here, we have a issues in  https://github.com/QT-DevOps/DevOpsIssues/issues 

Please post ur issues here.

**Comment by BRAHMAREDDYV** [comment]
Please share the playbook

**Comment by BRAHMAREDDYV** [comment]
i did not see the date sorry for that  

thq

**Comment by VENKATAREDDYVENNA** [comment]
Hi Chinnadas
based on these lines 
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
Nov 20 17:00:32 ip-172-31-22-72 apache2[8625]: (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80

I am thinking that port "80" is using by some other service, Please check whether any service is running port 80.

check the port is in use or not by typing below command
netstat -tpuln |grep 80
